JOIN

[없어진 기록 찾기]

SELECT A.ANIMAL_ID
     , A.NAME
  FROM ANIMAL_OUTS A LEFT JOIN ANIMAL_INS B
                     ON A.ANIMAL_ID = B.ANIMAL_ID
 WHERE B.ANIMAL_ID IS NULL
ORDER BY A.ANIMAL_ID;



[있었는데요 없었습니다]

SELECT A.ANIMAL_ID
     , A.NAME
  FROM ANIMAL_INS A 
     , ANIMAL_OUTS B
 WHERE A.ANIMAL_ID = B.ANIMAL_ID
   AND A.DATETIME > B.DATETIME
ORDER BY A.DATETIME



[오랜 기간 보호한 동물(1)]

   SELECT A.NAME
        , A.DATETIME
     FROM ANIMAL_INS A 
LEFT JOIN ANIMAL_OUTS B
       ON A.ANIMAL_ID = B.ANIMAL_ID
    WHERE B.ANIMAL_ID IS NULL
 ORDER BY DATETIME
    LIMIT 3;



[보호소에서 중성화한 동물]

SELECT A.ANIMAL_ID
     , A.ANIMAL_TYPE
     , A.NAME
  FROM ANIMAL_INS A
     , ANIMAL_OUTS B
 WHERE A.ANIMAL_ID = B.ANIMAL_ID 
   AND A.SEX_UPON_INTAKE LIKE '%Intact%'
   AND (B.SEX_UPON_OUTCOME LIKE '%Spayed%'
        OR 
        B.SEX_UPON_OUTCOME LIKE '%Neutered%')
ORDER BY ANIMAL_ID;